server:
  port: 8877
mybatis:
 configuration:
   map-underscore-to-camel-case: true
spring:
  # ???????
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idiom?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: linhuantan
    password: root
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
